#!/usr/bin/env bash

# Enable UFW
sudo apt-get install ufw

# Show UFW status
sudo ufw status

# Enable UFW and set default policies
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow incoming traffic on specific ports
sudo ufw allow 22/tcp  # SSH
sudo ufw allow 80/tcp  # HTTP
sudo ufw allow 443/tcp # HTTPS
